version: 6.0.1.{build}

install:
  - cmd: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - cmd: git submodule -q update --init          

  - cmd: cd lib\FluentSharp.NUnit
  - cmd: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - cmd: git submodule -q update --init          
  - cmd: nuget restore
  - cmd: msbuild FluentSharp.NUnit.sln
  - cmd: cd ../../

before_build:
  - nuget restore

build:
  project: FluentSharp.CoreLib.sln
  verbosity: minimal


assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_test:
  - nuget pack src/FluentSharp.CoreLib.csproj -Version %appveyor_build_version% 

artifacts:
  - path: '*.nupkg' 

deploy:
  provider: NuGet  
  api_key:
    secure: x5HJMlw9Ik+PLRN6tpUy4lbSz3gPMSHcjQRHjuUn/URW8Z45NoUhvIs/yNi3Kpfd
  artifact: /.*\.nupkg/