#version: 6.0.1.{build}

install:
  - cmd: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - cmd: git submodule -q update --init          


build:
  project: FluentSharp.CoreLib.sln
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

artifacts:
  - path: test.zip
    name: MyApp