version: 6.0.1.{build}

install:
  - cmd: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - cmd: git submodule -q update --init          

  - cmd: cd lib\FluentSharp.NUnit
  - cmd: dir
  - cmd: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - cmd: git submodule -q update --init          
  - cmd: nuget restore
  - cmd: msbuild FluentSharp.NUnit.sln
  - cmd: cd ../../
  - cmd: dir



before_build:
  - nuget restore

build:
  project: FluentSharp.CoreLib.sln
  verbosity: minimal